// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-hC_DkLQK2V67hzdkM6Bhe-pDIL0hr3c',
    appId: '1:519712667928:web:ee637d369f74c0768f466d',
    messagingSenderId: '519712667928',
    projectId: 'atm-movie',
    authDomain: 'atm-movie.firebaseapp.com',
    storageBucket: 'atm-movie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHLp8_0HFNMLFRIxPgSSv_x1l2FCjtj_k',
    appId: '1:519712667928:android:e7b196327e1821ab8f466d',
    messagingSenderId: '519712667928',
    projectId: 'atm-movie',
    storageBucket: 'atm-movie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXn8a0fG55Dnakm5kr6c_KtkXG154BeSQ',
    appId: '1:519712667928:ios:91f6a3bfb7bc2a6e8f466d',
    messagingSenderId: '519712667928',
    projectId: 'atm-movie',
    storageBucket: 'atm-movie.firebasestorage.app',
    iosClientId:
        '519712667928-22dag1hbpipob8lpq50hf1ihvlrkioh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.atmMovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXn8a0fG55Dnakm5kr6c_KtkXG154BeSQ',
    appId: '1:519712667928:ios:91f6a3bfb7bc2a6e8f466d',
    messagingSenderId: '519712667928',
    projectId: 'atm-movie',
    storageBucket: 'atm-movie.firebasestorage.app',
    iosClientId:
        '519712667928-22dag1hbpipob8lpq50hf1ihvlrkioh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.atmMovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-hC_DkLQK2V67hzdkM6Bhe-pDIL0hr3c',
    appId: '1:519712667928:web:0dca10941e91d9508f466d',
    messagingSenderId: '519712667928',
    projectId: 'atm-movie',
    authDomain: 'atm-movie.firebaseapp.com',
    storageBucket: 'atm-movie.firebasestorage.app',
  );
}
